name: my_exam
description: For spesific platform

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # design
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.2.0
  cached_network_image: ^3.2.0
  flutter_staggered_grid_view: ^0.6.1

  # firebase
  firebase_core: ^1.20.0
  firebase_auth: ^3.6.2
  firebase_database: ^9.1.0
  firebase_storage: ^10.3.4
  firebase_crashlytics: ^2.8.6
  firebase_remote_config: ^2.0.14


  # storage
  shared_preferences: ^2.0.15

  # image
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
